### ISSUE TITLE
How to use with Tensorflow 2.0 or 2.1?

### ISSUE THREAD

**Issue by Bigous** [KristianHolsheimer/keras-gym#12]
Hi, is there a way to use keras_gym with tensorflow 2.x?

**Comment by KristianHolsheimer** [comment]
Hi there, keras-gym should work with tf2. I did have to disable eager execution, which iirc didn't play nice with [`clone_model`](https://www.tensorflow.org/api_docs/python/tf/keras/models/clone_model), which is used internally to create "target network" models.

If you're experiencing issues, I'll be happy to help you out

**Comment by Bigous** [comment]
I'm sorry.

You are correct.

My problem is actually running it on tensorflow on windows.
When I use a docker image of tensorflow on ubuntu, almost everything works - except for the rendering part.

On my environment I'm receiving the message below, do you know what it could be?

`WARNING:tensorflow:Output tf_op_layer_huber_loss/weighted_loss/value missing from loss dictionary. We assume this was done on purpose. The fit and evaluate APIs will not be expecting any data to be passed to tf_op_layer_huber_loss/weighted_loss/value.
XXX lineno: 253, opcode: 47
Traceback (most recent call last):
  File "sarsa.py", line 20, in <module>
    q = km.QTypeI(func, update_strategy='sarsa')
  File "C:\Users\richard.natal\AppData\Local\Continuum\anaconda3\envs\tf2-cpu\lib\site-packages\keras_gym\core\value_q.py", line 40, in __init__
    self._init_models()
  File "C:\Users\richard.natal\AppData\Local\Continuum\anaconda3\envs\tf2-cpu\lib\site-packages\keras_gym\core\value_q.py", line 412, in _init_models
    self.target_model = self._create_target_model(self.predict_model)
  File "C:\Users\richard.natal\AppData\Local\Continuum\anaconda3\envs\tf2-cpu\lib\site-packages\keras_gym\core\base.py", line 76, in _create_target_model
    target_model = keras.models.clone_model(model)
  File "C:\Users\richard.natal\AppData\Local\Continuum\anaconda3\envs\tf2-cpu\lib\site-packages\tensorflow_core\python\keras\models.py", line 422, in clone_model
    model, input_tensors=input_tensors, layer_fn=clone_function)
  File "C:\Users\richard.natal\AppData\Local\Continuum\anaconda3\envs\tf2-cpu\lib\site-packages\tensorflow_core\python\keras\models.py", line 195, in _clone_functional_model
    created_layers=created_layers))
  File "C:\Users\richard.natal\AppData\Local\Continuum\anaconda3\envs\tf2-cpu\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1852, in reconstruct_from_config
    process_node(layer, node_data)
  File "C:\Users\richard.natal\AppData\Local\Continuum\anaconda3\envs\tf2-cpu\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1799, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "C:\Users\richard.natal\AppData\Local\Continuum\anaconda3\envs\tf2-cpu\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 847, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\Users\richard.natal\AppData\Local\Continuum\anaconda3\envs\tf2-cpu\lib\site-packages\tensorflow_core\python\keras\layers\core.py", line 795, in call
    return self.function(inputs, **arguments)
  File "C:/Users/richard.natal/AppData/Local/Continuum/anaconda3/envs/tf2-cpu/lib/site-packages/keras_gym/core/function_approximator.py", line 253, in kronecker_product
    S, A = args
SystemError: unknown opcode`

I did run some things on it like the [model to predict the wine price.](https://blog.tensorflow.org/2018/04/predicting-price-of-wine-with-keras-api-tensorflow.html)
